pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/brownc61/ci-cd-flask-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t yourdockerhubusername/flask-ci-app .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-creds-id', url: '']) {
                    sh 'docker push yourdockerhubusername/flask-ci-app'
                }
            }
        }
    }
}
